"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ["BACKEND_SECRET_KEY"]

DEBUG = eval(os.getenv("BACKEND_DEBUG"))

ALLOWED_HOSTS = os.getenv("BACKEND_ALLOWED_HOSTS").split(",")

INSTALLED_APPS = [
    'simpleui',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
    'validators.apps.ValidatorsConfig',
    'bootstrap3',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'django_apscheduler',
    'scheduler.apps.SchedulerConfig',
    'import_export',
    'django_prometheus',
]

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
    'apis.util.api_time_middleware.ApiTimeMiddleware',
    'apis.util.exception_middleware.ExceptionMiddleware',
]
IMPORT_EXPORT_USE_TRANSACTIONS = True

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ["BACKEND_DATABASE"],
        'USER': os.environ["BACKEND_DATABASE_USER"],
        'PASSWORD': os.environ["BACKEND_DATABASE_PASSWORD"],
        'HOST': os.environ["BACKEND_DATABASE_HOST"],
        'PORT': os.environ["BACKEND_DATABASE_PORT"],
        'OPTIONS': {
            'ssl': {} if os.environ["BACKEND_DATABASE_CA"] == ''
            else {
                'ca': os.environ["BACKEND_DATABASE_CA"],
            }
        }
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.PyLibMCCache',
        'LOCATION': os.getenv('BACKEND_CACHES_LOCATION')
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR.parent.parent / "shared" / "static"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

BOOTSTRAP3 = {
    'include_jquery': True,
}

JWT = {
    'SECRET_KEY': os.environ["BACKEND_JWT_SECRET_KEY"],
}

BACKEND = {
    'network': os.getenv("BACKEND_NETWORK"),
}

ETH = {
    'api_url': os.getenv("BACKEND_ETHERSCAN_API_URL"),
    'api_key': os.environ["BACKEND_ETHERSCAN_API_KEY"],
    'network': os.getenv("BACKEND_ETH_DEPOSIT_NETWORK"),
    'chainid': os.getenv("BACKEND_ETH_CHAIN_ID"),
}

ETH1 = {
    'endpoint': os.environ["BACKEND_ETH1_ENDPOINT"],
}

ETH2 = {
    'endpoint': os.environ["BACKEND_ETH2_ENDPOINT"],
}

STVAULT = {
    'cli_api_url': os.environ["STVAULT_CLI_API_URL"],
}

# Internal service token (for service-to-service calls)
INTERNAL_SERVICE_TOKEN = os.getenv("BACKEND_INTERNAL_SERVICE_TOKEN", "")
# 内部服务 IP 白名单（逗号分隔，支持单 IP 或 CIDR，例如 "10.0.0.0/8,192.168.1.5"）
INTERNAL_SERVICE_IP_WHITELIST = [
    ip.strip()
    for ip in os.getenv("BACKEND_INTERNAL_SERVICE_IP_WHITELIST", "").split(",")
    if ip.strip()
]

# 前端 RPC 代理：将 JSON-RPC 请求转发到此 upstream，避免在前端 bundle 中暴露 provider key。
RPC_MAINNET_UPSTREAM = os.getenv("BACKEND_RPC_MAINNET_UPSTREAM", "")
RPC_HOODI_UPSTREAM = os.getenv("BACKEND_RPC_HOODI_UPSTREAM", "")

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ["BACKEND_EMAIL_HOST"]
EMAIL_PORT = os.environ["BACKEND_EMAIL_PORT"]
EMAIL_HOST_USER = os.environ["BACKEND_EMAIL_HOST_USER"]
EMAIL_HOST_PASSWORD = os.environ["BACKEND_EMAIL_HOST_PASSWORD"]
EMAIL_FROM = os.environ["BACKEND_EMAIL_FROM"]
EMAIL_USE_TLS = True
EMAIL_SEND_ENABLE = True

CSRF_TRUSTED_ORIGINS = os.getenv("BACKEND_CSRF_TRUSTED_ORIGINS").split(",")
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = os.getenv("BACKEND_CORS_ORIGIN_WHITELIST").split(",")
CORS_ALLOW_METHODS = ('DELETE', 'GET', 'OPTIONS', 'PATCH', 'POST', 'PUT', 'VIEW',)
CORS_ALLOW_HEADERS = (
    'XMLHttpRequest',
    'X_FILENAME',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'Pragma',
    'Pool-Id',
)

APP_CONFIG = [
    {
        'key': 'fee_commission',
        'value': '0.1',
        'value_type': 'string',
        'remark': 'Block reward commission rate',
    },
    {
        'key': 'mev_commission',
        'value': '0.1',
        'value_type': 'string',
        'remark': 'MEV reward commission rate',
    },
    {
        'key': 'pool_fee_commission',
        'value': '1',
        'value_type': 'string',
        'remark': 'Pool block reward commission rate',
    },
    {
        'key': 'pool_mev_commission',
        'value': '1',
        'value_type': 'string',
        'remark': 'Pool MEV reward commission rate',
    },
    {
        'key': 'eth_epoch_genesis_time',
        'value': 1606824023,
        'value_type': 'int',
        'remark': 'Beacon chain genesis time',
    },
    {
        'key': 'eth_epoch_duration_seconds',
        'value': 384,
        'value_type': 'int',
        'remark': 'Epoch duration in seconds',
    },
    {
        'key': 'eth_slot_duration_seconds',
        'value': 12,
        'value_type': 'int',
        'remark': 'Slot duration in seconds',
    },
    {
        'key': 'token_expires_in',
        'value': 86400,
        'value_type': 'int',
        'remark': 'Session token lifetime (seconds)',
    },
    {
        'key': 'ding_enable',
        'value': 1,
        'value_type': 'int',
        'remark': 'DingTalk notifications enabled',
    },
]

DING = {
    'endpoint': 'https://oapi.dingtalk.com/robot/send?access_token=',
    'secret_access_key': os.getenv("BACKEND_DING_SECRET_ACCESS_KEY"),
    'enable': eval(os.getenv("BACKEND_DING_ENABLE")),
    'secret_access_keys': {
        'daily_report': os.getenv("BACKEND_DING_SECRET_ACCESS_KEY_DAILY"),
        'hourly_report': os.getenv("BACKEND_DING_SECRET_ACCESS_KEY_HOURLY"),
        'notice_report': os.getenv("BACKEND_DING_SECRET_ACCESS_KEY_NOTICE"),
        'alarm_report': os.getenv("BACKEND_DING_SECRET_ACCESS_KEY_ALARM"),
        'financial_report': os.getenv("BACKEND_DING_SECRET_ACCESS_FINANCIAL_REPORT"),
    }
}

LARK = {
    'enable': eval(os.getenv("BACKEND_LARK_ENABLE")),
    'endpoint': 'https://open.feishu.cn/open-apis/bot/v2/hook/',
    'secret_access_keys': {
        'daily_report': os.getenv("BACKEND_LARK_SECRET_ACCESS_KEY_DAILY"),
        'hourly_report': os.getenv("BACKEND_LARK_SECRET_ACCESS_KEY_HOURLY"),
        'notice_report': os.getenv("BACKEND_LARK_SECRET_ACCESS_KEY_NOTICE"),
        'alarm_report': os.getenv("BACKEND_LARK_SECRET_ACCESS_KEY_ALARM"),
        'financial_report': os.getenv("BACKEND_LARK_SECRET_ACCESS_FINANCIAL_REPORT"),
    }
}

LOGGING_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOGGING_DIR):
    os.makedirs(LOGGING_DIR)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGGING_DIR, 'django.log'),
            'maxBytes': 50 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGGING_DIR, 'errors.log'),
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': os.getenv("BACKEND_LOGGING_HANDLERS").split(","),
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': os.getenv("BACKEND_LOGGING_HANDLERS").split(","),
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
